### PR TITLE
Make group and permissions swappable on non-standard projects

### LINKED ISSUE #7: Using a custom `Group` and associated permissions
**Is your feature request related to a problem? Please describe.**

In my project, instead of using the `Group` model, I have an `Entity` model, subclassed with two other models `District` and `Irrigator`, allowing me to have multi-level user groupings (e.g., both subclasses are Entities, but Irrigators are ForeignKeys to District, allowing an organizational hierarchy). I know other folks are doing similar things using packages like django-organizations. Additionally, I also use custom permissions.

Unfortunately, `interaction_group` in `AutomationTaskModel` and the `Form` Node are currently directly tied to Django's default `Group` and `Permission` models.

**Describe the solution you'd like**

I would like to break away from forcing use of the built-in `Group` and `Permission` models to allow more flexibility. Keep these as defaults for simplicity, but allow overriding.

In the project's settings, allow specification of the "Group" model to use (in my case, it would be my `Entity` model), with a default fallback to `auth.Group`. Use this setting in models.py and flow.py.

For Permission, it's slightly more complex. We would need to allow user to override `get_users_with_permission()` for the `Form` Node in flow.py with their own permission-checking method, while falling back to your existing `get_users_with_permission()` if no override is specified.

This could be accomplished in much the same way as django has a default `make_key()` function for cache keys, but allows a custom function to override the default.

See:
- https://docs.djangoproject.com/en/3.2/topics/cache/#cache-key-transformation
- https://github.com/django/django/blob/301a85a12f3c2c9427c7ff581fd4683bab1f29f6/django/core/cache/backends/base.py#L42

---

I would be happy to develop a PR to provide this functionality if that's okay.

### PR DESCRIPTION
**Pull request by jacklinke**
This PR is to allow Django Automations to work in projects that do not use Django's standard `Group` and `Permission` models, and should resolve #7 

Settings are made available for specifying which model to use in place of `auth.Group`, and which methods to use for getting users with permissions in a Form or task, while falling back to the defaults if these settings are not specified. There is a system check to ensure that either all three of the associated settings are set, or that none are.

- [x] Swappable `Group` model
- [x] Swappable `get_users_with_permission` method for `flow.Form`
- [x] Swappable `get_users_with_permission` method for `AutomationTaskModel`
- [x] Add system check for settings
- [x] Update documentation to explain the settings and how to use them

---

I would love feedback or ideas for improving this further. Hope others will find this useful.

### CODE REVIEW

**Comment by fsbraun** [comment]
This seems a well-thought through way of abstracting form User and Group models!  I have no projects which do that right now. You have already started to introduce some tests. Can I encourage you to add tests that actually swap the User and Group models? I really would love to keep the coverage high.

**Comment by fsbraun** [comment]
PS: Nice move to use MethodType for swapping.

**Comment by jacklinke** [comment]
> Can I encourage you to add tests that actually swap the User and Group models?

Absolutely, though it may have to wait until tomorrow.

**Comment by jacklinke** [comment]
Alright, I think it's getting there. Tests pass, added some coverage for swapping models and methods. Had to get a bit creative due to challenges in using test-only models and learning more about `@override_settings` than I ever thought I'd need 😄

Please let me know if you have any recommendations.

**Comment by jacklinke** [comment]
One big change in this PR is that I moved tests to a separate directory to allow for test-specific models. This was a bit of a challenge due to issues that can occur when creating models in tests, but was resolved with changes to the __init__.py in the new directory (see https://code.djangoproject.com/ticket/7835#comment:46)

Due to the way `@override_settings` works, in order to test the changes to method swaps, I had to modify the methods that call the swaps to be able to take the overridden test settings (defaulting to django.conf.settings).

```
flow.swap_users_with_permission_form_method(settings_conf=settings)
models.swap_users_with_permission_model_method(AutomationTaskModel, settings_conf=settings)
```

I had to do the same the the settings I added within automations.settings.py to retrieve the correct package-level settings based on the overridden test settings (defaulting to django.conf.settings).

If anything in the PR needs changing or further explanation, please let me know.

**Pull request merged**
